# Generated by Django 2.2.1 on 2019-05-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='to_do_history',
            field=models.ManyToManyField(related_name='users', through='todo.History', to='todo.ToDoText', verbose_name='히스토리'),
        ),
    ]
