# Generated by Django 2.2.1 on 2019-05-18 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_feed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='user',
        ),
    ]
