# Generated by Django 2.2.1 on 2019-05-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
        ('account', '0002_user_to_do_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='to_do_history',
        ),
        migrations.AddField(
            model_name='user',
            name='to_do',
            field=models.ManyToManyField(related_name='users', to='todo.ToDoText', verbose_name='히스토리'),
        ),
    ]
