# Generated by Django 2.2.1 on 2019-05-18 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190519_0325'),
        ('account', '0004_remove_user_to_do'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=True, verbose_name='마쳤냐')),
                ('to_do', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='todo.ToDoText', verbose_name='to do')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '히스토리',
                'verbose_name_plural': '히스토리',
                'db_table': 'history',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='to_do',
            field=models.ManyToManyField(related_name='users', through='account.History', to='todo.ToDoText', verbose_name='히스토리'),
        ),
    ]
