# Generated by Django 2.2.1 on 2019-05-18 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190519_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='to_do',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed', to='todo.ToDoText'),
        ),
    ]
