# Generated by Django 2.2.1 on 2019-05-18 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190519_0325'),
        ('account', '0005_auto_20190519_0458'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='history',
            unique_together={('to_do', 'user')},
        ),
    ]
