# Generated by Django 2.2.1 on 2019-05-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190519_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정 날짜'),
        ),
    ]
