# Generated by Django 2.2.1 on 2019-05-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='to do')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
            ],
            options={
                'verbose_name': 'to do text',
                'verbose_name_plural': 'to do text',
                'db_table': 'to_do_text',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToDoKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('where', '어디서'), ('who', '누구와'), ('what', '무엇을'), ('how', '어떻게')], max_length=5, verbose_name='타입')),
                ('text', models.TextField(verbose_name='텍스트')),
            ],
            options={
                'verbose_name': 'to do 키워드',
                'verbose_name_plural': 'to do 키워드 목록',
                'db_table': 'to_do_keyword',
                'unique_together': {('type', 'text')},
            },
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_do_list', models.ManyToManyField(related_name='recommend', to='todo.ToDoText', verbose_name='추천 to do 목록')),
            ],
            options={
                'verbose_name': '추천 to do',
                'verbose_name_plural': '추천 to do',
                'db_table': 'recommend',
            },
        ),
    ]
